# https://docs.github.com/fr/enterprise-cloud@latest/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment
name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Node
        uses: pplancq/actions/setup-node@66e6d183d1cb9c8f9a4bd1a347c13bca6025ba6a # v1.1.3
        with:
          use-mise: "true"
          disabled-cache: true

      - name: Install package
        run: npm ci
